name: CI

on:
  push:
  pull_request:
    branches:
      - main 

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents:      read
      actions:       read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.0

      - name: Set up Go
        uses: actions/setup-go@v6.1.0
        with:
          go-version: '1.25.5'
          cache: true

      - name: Install dependencies
        run: make mod-download

      - name: Run Analze
        run: |
          make lint
          make vet
          make check
    
      - name: Run tests with coverage and report
        run: make test-with-coverage-and-report

      - name: Convert test report to JUnit
        uses: dorny/test-reporter@v2.3.0
        if: always()
        with:
          name: Go Tests
          path: _output/test-report.json
          reporter: golang-json

      - name: Check test coverage
        uses: vladopajic/go-test-coverage/action/source@v2.18.0
        if: always()
        with:
          config: ./.testcoverage.yaml