name: CI

on:
  push:
  pull_request:
    branches:
      - main 

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.x'
          cache: true

      - name: Install staticcheck and govulncheck
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@latest
          go install golang.org/x/vuln/cmd/govulncheck@latest

      - name: Install golangci-lint
        uses: golangci/golangci-lint-action@v9.1.0
        with:
          version: latest
          install-only: true

      - name: Run Makefile checks
        run: |
          make lint
          make vet
          make check
    
      - name: Run tests with coverage
        run: |
          mkdir -p build
          go test ./... -covermode=atomic -coverprofile=build/coverage.out -coverpkg=./... -json > build/testreport.json

      - name: Convert test report to JUnit
        uses: dorny/test-reporter@v2
        if: always()
        with:
          name: Go Tests
          path: build/testreport.json
          reporter: golang-json


      - name: check test coverage
        uses: vladopajic/go-test-coverage/action/source@v2
        if: always()
        with:
          config: ./.testcoverage.yaml
          profile: build/coverage.out